import type { Metadata } from "next";
import "./globals.css";
import { Provider } from "@component/components/ui/provider"
import { Noto_Serif, Roboto_Slab } from 'next/font/google'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const primaryFont = Noto_Serif({ subsets: ['cyrillic'] })
const secondaryFont = Roboto_Slab({ subsets: ['cyrillic'] })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={`${primaryFont.className} ${secondaryFont.className}`}>
        <Provider>{children}</Provider>
    </body>
    </html>
  );
}
